# Generated by Django 3.0.7 on 2021-01-28 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(7)])),
                ('rating', models.FloatField()),
                ('distrito', models.CharField(max_length=20)),
            ],
        ),
    ]
