# Generated by Django 3.1.5 on 2021-01-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rating',
            field=models.FloatField(default=8),
        ),
    ]
